version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running build (if any)..."
      - npm run build || true
      - echo "Cleaning node_modules to keep artifact small"
      - rm -rf node_modules
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - '**/*'
  discard-paths: no
